language: node_js
node_js:
  - "6.11.5"
before_install:
  - npm i -g npm@4.0.5
cache: npm
script:
  - npm run build
deploy:
  provider: pages
  repo: embriosupport-dev-page
  skip_cleanup: true
  github_token: $github_token 
  keep_history: true
  on:
    branch: master    