language: node_js
node_js:
  - 12
before_install:
  - npm i -g npm@6.14.4
cache: npm
script:
# マスターブランチ以外の場合、接続先DBをステージング環境用に切り替える。（フラグを参照し、prod.dev.jsで分岐している）
  - if [ "$TRAVIS_BRANCH" != "master" ]; then npm config set stagingdb "true"; fi
  - npm run build
# github-pagesにデプロイする際、/dist以下にデプロイする必要があるため、ディレクトリを明示的にコピーする。  
before_deploy: |
  mkdir gh_dist
  mv ./dist ./gh_dist 

# feature以下のブランチの場合は、dev環境にデプロイ。masterの場合はprod環境にデプロイ。
deploy:
  - provider: pages
    repo: direboar/embriosupport-dev-page
    target_branch : master
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir : ./gh_dist
    verbose : true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^feature
  - provider: pages
    repo: direboar/embriosupport-prod-page
    target_branch : master
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir : ./gh_dist
    verbose : true
    on:
      branch: master
